/*

Highly divisible triangular number
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

*/

#include <math.h>
#include <stdio.h>

int get_factors(int);

int main(int argc, char *argv[])
{
	int k;
	for(k = 2; k < 100000000; k++)
	{
		if(get_factors((k * (k+1)) / 2) > 500){ // formula to generate triangular number: n(n+1)/2
			printf("%d\n", (k * (k+1)) / 2);
			break;
		}
	}	
	return 0;
}

int get_factors(int n)
{
	int i;
	int limit = n;
	int count = 0;
	
	for(i = 1; i < limit; ++i)
	{
		if(n % i == 0){
			limit = n / i;
			if(limit != i)
				count++;
			count++;
		}
	}
	return count;
}
