#!/usr/bin/python3

"""
Triangular, pentagonal, and hexagonal
Problem 45

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle        Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

# slow brute-force method

y = [(n * (3 * n - 1)) // 2 for n in range(100001)]
z = [(n * (2 * n - 1)) for n in range(100001)]

for i in y:
	if i in z and i > 40755:
		print(i)
		break
